package GUI;

/**
 * Auswahl ansteuerbarer Ansichten
 */
public enum Ansicht {
    STARTSCREEN,
    HAUPTMENUE,
    LOKALE_SPIELER_WAEHLEN,
    SPIELKONFIGURATION,
    SCHIFFE_ANORDNEN_LINKS,
    SCHIFFE_ANORDNEN_RECHTS,
    SPIEL_SPIELEN,
    SPIELRUNDE_BEENDET,
    NETZWERKMODUS_WAEHLEN,
    NETZWERKSPIEL_ERSTELLEN,
    WARTE_AUF_CLIENT,
    VERBINDE_MIT_HOST,
    WARTE_AUF_HOST_SPIELKONFIGURATION,
    NETZWERKABBRUCH,
    BESTENLISTE,
    SPIEL_LADEN,
    EINSTELLUNGEN,
    NICHT_VERFUEGBAR
}