package Administration.Enums;

public enum EAction
{
    UNDO,
    REDO,
    SPIEL_LADEN,
    SPIEL_LOESCHEN,
    SPIELRUNDE_SPEICHERN,
    BESTENLISTE_LEEREN,
    
    SPIELRUNDE_ABBRECHEN,
    NETZWERKDATEN_CLIENT_ABRUFBBAR,
    NETZWERK_SPIEL_ABBRECHEN,
    SPIELZUG_GEMACHT,
    SPIELFELD_KONFIGURATION_ABRUFBAR,
    SCHLACHT_BEGINNEN,
    LOKALE_SPIELER_ABRUFBAR,
    PROGRAMM_BEENDEN,
    ANSICHT_GEWAEHLT,
    MENUE_ZURUECK,
    SCHIFF_ROTIERT,
    SCHIFF_BEWEGT,
    SCHIFFE_AUTOMATISCH_PLATZIEREN,

    NETZWERK_VERBUNDEN,
    NETZWERK_NACHRICHT_SPIEL_STARTEN,
    NETZWERK_TIMEOUT,
    
    NETZWERK_HOST_DATEN_ABRUFBBAR,
    NETZWERK_MODUS_ABRUFBAR,

    NETZWERK_NACHRICHT_SPIEL_ABBRECHEN,
    NETZWERK_NACHRICHT_SPIELER_KONFIGURATION,
    NETZWERK_NACHRICHT_SPIELFELD_KONFIGURATION,
    NETZWERK_NACHRICHT_BEREIT,
    NETZWERK_NACHRICHT_SPIELZUG_SERVER,
    NETZWERK_NACHRICHT_SPIELZUG_CLIENT,
    NETZWERK_NACHRICHT_SPIELZUG_CLIENT_RETURN_FROM_SERVER,
    NETZWERK_NACHRICHT_GEWONNEN,
    NETZWERK_NACHRICHT_SCORES_AKTUALISIEREN,
    NETZWERK_NACHRICHT_AI_SPIELZUG_ANFRAGE_CLIENT,
    NETZWERK_NACHRICHT_AI_LETZTER_TREFFER_CLIENT,
    NETZWERK_NACHRICHT_AI_SCHIFF_ZERSTOERT_CLIENT
    
}