package Administration.Enums;

public enum EGameState {
    STARTSCREEN,
    HAUPTMENUE,
    LOKALE_SPIELER_WAEHLEN,
    SPIELKONFIGURATION,
    NETZWERK_SPIELKONFIGURATION,
    SCHIFFE_ANORDNEN_LINKS,
    SCHIFFE_ANORDNEN_RECHTS,
    NETZWERK_SCHIFFE_ANORDNEN,
    SPIEL_SPIELEN,
    SPIELRUNDE_BEENDET,
    NETZWERKMODUS_WAEHLEN,
    NETZWERKSPIEL_ERSTELLEN,
    WARTE_AUF_CLIENT,
    VERBINDE_MIT_HOST,
    WARTE_AUF_HOST_SPIELKONFIGURATION,
    NETZWERKABBRUCH,
    BESTENLISTE,
    SPIEL_LADEN,
    EINSTELLUNGEN,
}
